---
lint: |
  set -e
  ansible-lint
driver:
  name: docker
platforms:
  - name: instance-playbook
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../site.yml
verifier:
  name: testinfra
