---
lint: |
  set -e
  ansible-lint
driver:
  name: docker
platforms:
  - name: instance-playbook
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../site.yml
verifier:
  name: testinfra
